<?php
$z[0]=Array("global","",403,429);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",473,503);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",540,567);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1406,1441);
$z[3][4]['filename']="head.htm";
$z[4]=Array("type","\r\n      <h1>[field:typename /]</h1>\r\n      ",1690,1767);
$z[4][4]['typeid']="0";
$z[5]=Array("channel","\r\n        <li ><a href=\"[field:typeurl/]\">\r\n          <label>- </label>\r\n          [field:typename/]</a></li>\r\n        ",1789,2065);
$z[5][4]['row']="10";
$z[5][4]['type']="son";
$z[5][4]['col']="1";
$z[5][4]['currentstyle']="<li class='curr'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("field","",2918,2976);
$z[6][4]['name']="typeid";
$z[6][4]['function']="GetTopTypename(@me)";
$z[7]=Array("field","",3022,3051);
$z[7][4]['name']="position";
$z[8]=Array("field","",3119,3140);
$z[8][4]['name']="content";
$z[9]=Array("include","",3422,3459);
$z[9][4]['filename']="footer.htm";

?>