<?php
$z[0]=Array("field","",403,422);
$z[0][4]['name']="title";
$z[1]=Array("global","",423,449);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",490,512);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",552,603);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1442,1477);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","\r\n      <h1>[field:typename /]</h1>\r\n      ",1725,1802);
$z[5][4]['typeid']="8";
$z[6]=Array("channel","\r\n        <li ><a href=\"[field:typeurl/]\">\r\n          <label>- </label>\r\n          [field:typename/]</a></li>\r\n        ",1824,2100);
$z[6][4]['row']="10";
$z[6][4]['type']="son";
$z[6][4]['col']="1";
$z[6][4]['currentstyle']="<li class='curr'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[7]=Array("field","",2953,3011);
$z[7][4]['name']="typeid";
$z[7][4]['function']="GetTopTypename(@me)";
$z[8]=Array("field","",3057,3086);
$z[8][4]['name']="position";
$z[9]=Array("field","",3160,3179);
$z[9][4]['name']="title";
$z[10]=Array("field","",3216,3234);
$z[10][4]['name']="body";
$z[11]=Array("type","<a href=\"[field:typelink /]\">返 回</a>",3327,3407);
$z[11][4]['typeid']="0";
$z[11][4]['row']="1";
$z[12]=Array("prenext","",3414,3439);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",3476,3502);
$z[13][4]['get']="next";
$z[14]=Array("include","",3748,3785);
$z[14][4]['filename']="footer.htm";

?>