<div class="tsf"> 
        <!--新闻图片-->
        <div class="imgleft"><a  href="[field:arcurl/]"><img src="[field:picname/]"></a></div>
        <div class="news_test"> 
          <!--新闻标题-->
          <div class="tded"><a  href="[field:arcurl/]">[field:title /]</a></div>
          <div class="testdd">[field:infos/]...</div>
          <div class="view_m">
            <p><a href="[field:arcurl/]">View Details</a></p>
          </div>
        </div>
      </div>