<?php
$z[0]=Array("global","",551,577);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",832,858);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",902,932);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",969,996);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",1832,1867);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist","\r\n      <div class=\"tsf\"> \r\n        <!--新闻图片-->\r\n        <div class=\"imgleft\"><a  href=\"[field:arcurl/]\"><img src=\"[field:picname/]\"></a></div>\r\n        <div class=\"news_test\"> \r\n          <!--新闻标题-->\r\n          <div class=\"tded\"><a  href=\"[field:arcurl/]\">[field:title /]</a></div>\r\n          <div class=\"testdd\">[field:infos/]...</div>\r\n          <div class=\"view_m\">\r\n            <p><a href=\"[field:arcurl/]\">View Details</a></p>\r\n          </div>\r\n        </div>\r\n      </div>\r\n      ",4884,5482);
$z[5][4]['row']="8";
$z[5][4]['typeid']="8";
$z[5][4]['titlelen']="15";
$z[5][4]['infolen']="180";
$z[5][4]['orderby']="pubdate";
$z[6]=Array("include","",5597,5634);
$z[6][4]['filename']="footer.htm";

?>